services:

  # Postgres db for userdata
  postgres-user:
    image: postgres:15
    container_name: postgres_user
    environment:
      - POSTGRES_DB=userDB
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-user:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 5s

  # Postgres db for product data
  postgres-product:
    image: postgres:15
    container_name: postgres_product
    environment:
      - POSTGRES_DB=productsDB
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-product:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 5s

  # Postgres db for cart data
  postgres-cart:
    image: postgres:15
    container_name: postgres_cart
    environment:
      - POSTGRES_DB=cartDB
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5434:5432"
    volumes:
      - pgdata-cart:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 5s

  # Service for user
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user-service
    container_name: user-service
    depends_on:
      - postgres-user
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_URL=jdbc:postgresql://postgres-user:5432/userDB
      - jwt.secret=${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - backend
    env_file:
      - .env

  # Service for product
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service
    container_name: product-service
    depends_on:
      - postgres-product
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_URL=jdbc:postgresql://postgres-product:5432/productsDB
      - jwt.secret=${JWT_SECRET}
    ports:
      - "8081:8081"
    networks:
      - backend
    env_file:
      - .env

  # Service for cart
  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    image: cart-service
    container_name: cart-service
    depends_on:
      - postgres-cart
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_URL=jdbc:postgresql://postgres-cart:5432/cartDB
      - jwt.secret=${JWT_SECRET}
    ports:
      - "8082:8082"
    networks:
      - backend
    env_file:
      - .env

  # Service for Service Registry (Eureka)
  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    image: service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - backend

  # Service for API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    networks:
      - backend
    env_file:
      - .env

  # Redis Caching
  redis:
    image: redis:8.0-M04
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  backend:
    driver: bridge

volumes:
  pgdata-user:
  pgdata-product:
  pgdata-cart:
