services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=userDB
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 5s
      retries: 5

  user-service:
    image: user-service
    container_name: user-service
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_URL=jdbc:postgresql://postgres:5432/userDB
      - jwt.secret=${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata: