services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=userDB
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    networks:
      - backend

  user-service:
    build:
      context: .
    container_name: user-service
    depends_on:
      - postgres
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_URL=jdbc:postgresql://postgres:5432/userDB
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
